// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5bVTFxWJ0lhPAr7Qh1Az-_aVBKQ_6CrY',
    appId: '1:1073538739777:web:46288810ce88ddfbd7a0c0',
    messagingSenderId: '1073538739777',
    projectId: 'civic-connect-video-test',
    authDomain: 'civic-connect-video-test.firebaseapp.com',
    storageBucket: 'civic-connect-video-test.firebasestorage.app',
    measurementId: 'G-B28KZ6K5P6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArWoCl9lcAtUYj_8UkMiXsOXTbS1vgJkA',
    appId: '1:1073538739777:android:12c7b71e018cec62d7a0c0',
    messagingSenderId: '1073538739777',
    projectId: 'civic-connect-video-test',
    storageBucket: 'civic-connect-video-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCcAUlw68FxLXLK_w9jq7mrQIzTpPS2PU',
    appId: '1:1073538739777:ios:d58e44eac3f109a7d7a0c0',
    messagingSenderId: '1073538739777',
    projectId: 'civic-connect-video-test',
    storageBucket: 'civic-connect-video-test.firebasestorage.app',
    iosBundleId: 'com.example.civicConnectVideo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCcAUlw68FxLXLK_w9jq7mrQIzTpPS2PU',
    appId: '1:1073538739777:ios:d58e44eac3f109a7d7a0c0',
    messagingSenderId: '1073538739777',
    projectId: 'civic-connect-video-test',
    storageBucket: 'civic-connect-video-test.firebasestorage.app',
    iosBundleId: 'com.example.civicConnectVideo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5bVTFxWJ0lhPAr7Qh1Az-_aVBKQ_6CrY',
    appId: '1:1073538739777:web:cf804a0339e092eed7a0c0',
    messagingSenderId: '1073538739777',
    projectId: 'civic-connect-video-test',
    authDomain: 'civic-connect-video-test.firebaseapp.com',
    storageBucket: 'civic-connect-video-test.firebasestorage.app',
    measurementId: 'G-QL7ZJBPLXL',
  );
}
